const LANGUAGE_KEY = 'muscu_language';
const SUPPORTED_LANGUAGES = ['fr', 'en'];

const FR = {
  programNotFound: 'Programme introuvable.', lastProgramDelete: 'Crée ou importe un autre programme avant de supprimer le dernier programme disponible.',
  name: 'Nom', newProgram: 'Nouveau programme', block: 'Bloc', strength: 'Force', hypertrophy: 'Hypertrophie', endurance: 'Endurance', mixed: 'Mixte', technique: 'Technique', remove: 'Retirer', errorOccurred: 'Une erreur est survenue.',
  restBetweenExercises: 'Repos entre exercices (s)', drops: 'Nombre de baisses', loadReduction: 'Réduction de charge (%)', target: 'Cible', pauses: 'Nombre de pauses', pauseDuration: 'Durée des pauses (s)', activationReps: "Reps d’activation", miniSetReps: 'Reps par mini-série', techniqueRest: 'Repos technique (s)', clusterReps: 'Reps par cluster', intraSetRest: 'Repos intra-série (s)', exerciseCount: "Nombre d’exercices", partialReps: 'Reps partielles',
  exportError: "Erreur lors du téléchargement",
  settings: 'Paramètres', language: 'Langue', french: 'Français', english: 'Anglais', appearance: 'Apparence', theme: 'Thème', themeDark: 'Sombre', themeLight: 'Clair', visualStyle: 'Style visuel', visualStyleDesc: 'Change l’habillage de l’application.', styleDefault: 'Classique', stylePiste: 'Piste', styleNothing: 'Nothing', homeEyebrowNext: 'Prochaine séance suggérée', homeEyebrowSessions: 'Tes séances', privacyPolicy: 'Politique de confidentialité', help: 'Aide', replayGuide: 'Revoir le guide', replayGuideDesc: 'Relance la visite guidée de l’application.', replay: 'Revoir', accessibility: 'Accessibilité et confort', textSize: 'Taille du texte', textSizeDesc: 'Agrandis l’interface sans changer les données.', textSizeNormal: 'Normale', textSizeLarge: 'Grande', textSizeXLarge: 'Très grande', highContrast: 'Contraste renforcé', reduceMotion: 'Réduire les animations', hapticFeedback: 'Vibration en fin de repos', hapticFeedbackDesc: 'Disponible seulement sur les appareils compatibles.', keepScreenAwake: 'Garder l’écran allumé', keepScreenAwakeDesc: 'Uniquement pendant une séance active.', home: 'Accueil', calendar: 'Calendrier', stats: 'Stats', programs: 'Programmes',
  supplements: 'Compléments', supplementsSubtitle: 'Gère tes prises quotidiennes', supplementsProgress: '{taken}/{total} pris aujourd’hui', supplementsEmptyHome: 'Ajoute tes compléments pour les suivre chaque jour.', addSupplements: 'Ajouter', manage: 'Gérer', supplementName: 'Nom du complément', supplementNamePlaceholder: 'ex. Créatine', dose: 'Dose', unit: 'Unité', addSupplement: 'Ajouter le complément', mySupplements: 'Mes compléments', perDay: 'par jour', supplementsEmpty: 'Aucun complément pour le moment.', deleteSupplementConfirm: 'Supprimer définitivement « {name} » de tes compléments ?', supplementsTakenCalendar: 'Compléments pris', supplementsMissingCalendar: 'Compléments incomplets', supplementsPartialCalendar: 'Compléments partiellement pris',
  supplementsNotificationPending: '💊 Compléments : à prendre', supplementsNotificationComplete: '💊 Compléments : ✅',
  workouts: 'Séances', streak: 'Streak 🔥', thisMonth: 'Ce mois', rollingCycle: 'Cycle roulant — 1 jour sur 2', nextSuggested: 'Prochaine séance suggérée :',
  onboardingTitle: 'Bienvenue dans Muscu Tracker', onboardingDescription: 'Choisis un point de départ adapté. Tout restera modifiable.', onboardingProgramsLabel: 'Programmes proposés', onboardingBeginner: 'Full body débutant', onboardingBeginnerDesc: '2 séances à alterner · 3 fois par semaine · bases simples', onboardingHypertrophy: 'Haut/Bas hypertrophie', onboardingHypertrophyDesc: '4 séances par semaine · volume équilibré · intermédiaire', onboardingStrength: 'Force, tractions et deadlift', onboardingStrengthDesc: 'Cycle A/B/C/D · un jour sur deux · avancé', recommended: 'Recommandé', onboardingCreate: 'Créer mon programme', onboardingCreateDesc: 'Pars d’un programme vierge et configure chaque séance.', onboardingImport: 'Importer un programme', onboardingImportDesc: 'Ajoute un programme depuis une sauvegarde JSON.', onboardingSkip: 'Plus tard', homeEmptyTitle: 'Pas encore de programme', homeEmptyDescription: 'Crée un programme sur mesure ou pars d’un modèle prêt à l’emploi pour commencer à t’entraîner.', homeEmptyCreate: 'Créer mon programme', homeEmptyExplore: 'Découvrir des modèles', tourSkip: 'Passer le guide', tourNext: 'Suivant', tourDone: 'C’est parti', tourStep: 'Étape {current} sur {total}', tourHomeTitle: 'Ton accueil', tourHomeDesc: 'Retrouve tes séances, ta streak et ton activité du mois en un coup d’œil.', tourSupplementsTitle: 'Tes compléments', tourSupplementsDesc: 'Ajoute tes compléments ici, puis coche chaque prise du jour en un tap.', tourSessionsTitle: 'Lancer une séance', tourSessionsDesc: 'Tape une séance pour la démarrer directement depuis l’accueil.', tourCalendarTitle: 'Ton historique', tourCalendarDesc: 'Chaque couleur correspond à une séance. Déplie la légende pour t’y retrouver, et tape un jour pour voir le détail.', tourStatsTitle: 'Tes statistiques', tourStatsDesc: 'Suis l’évolution de tes charges et de tes records, groupés par push/pull/jambes.', tourProgramsTitle: 'Tes programmes', tourProgramsDesc: 'Personnalise entièrement tes séances : exercices, séries, et même des techniques d’intensification comme le drop set ou les myo-reps.', tourSettingsTitle: 'Les réglages', tourSettingsDesc: 'Langue, thème, accessibilité, notifications : tout se règle ici.',
  tipRestFullscreenTitle: 'Repos en plein écran', tipRestFullscreenDesc: 'Le repos s’ouvre en plein écran par défaut. Utilise « Réduire » pour revenir à la barre compacte.', tipSupplementsCheckTitle: 'Marque tes prises', tipSupplementsCheckDesc: 'Tape sur un complément pour le marquer pris aujourd’hui.', tipTechniqueTitle: 'Techniques d’intensification', tipTechniqueDesc: 'Choisis ici une technique comme le drop set, les myo-reps ou le rest-pause pour cet exercice.', tipSettingsTitle: 'Encore plus de réglages', tipSettingsDesc: 'Découvre aussi le style visuel Piste/Nothing, et plus bas l’accessibilité (taille de texte, contraste, vibrations) et les rappels de séance.', gotIt: 'Compris', dismissTip: 'Fermer l’astuce',
  finish: 'Terminer', back: 'Retour', previousMonth: 'Mois précédent', nextMonth: 'Mois suivant', consecutiveWorkouts: 'séances consécutives', consecutiveWeeks: 'semaines réussies consécutives', statistics: 'Statistiques', performanceProgress: 'Progression de tes performances', workoutActions: 'Actions de la séance', editWorkout: 'Modifier la séance', editWorkoutDesc: 'Ajoute ou remplace des exercices pour cette séance uniquement.', discardWorkout: 'Abandonner la séance', discardWorkoutConfirm: 'Abandonner « {name} » ? Le repos et la sauvegarde de cette séance en cours seront supprimés.', bonusBlock: 'Bloc bonus {count}', selectBlock: 'Bloc à modifier', newBonusBlock: '＋ Nouveau bloc bonus', blockName: 'Nom du bloc', blockType: 'Type de bloc', superset: 'Superset', addExerciseToWorkout: 'Ajouter un exercice', bonusOnly: 'Les changements ne modifient pas ton programme.', replace: 'Remplacer', replaceExercise: "Changer d'exercice", recordedExercises: 'Exercices enregistrés', editingRecordedWorkout: "Modification d'une séance enregistrée", editRecordedWorkout: 'Modifier cette séance', recordedWorkoutSaved: 'Séance modifiée ✓',
  oneMonth: '1 mois', threeMonths: '3 mois', sixMonths: '6 mois', all: 'Tout', liftedWeight: 'Poids soulevé (kg)', repetitions: 'Répétitions', noStats: "Commence à t'entraîner pour voir tes stats !",
  statsRecordsTitle: 'Records personnels', statsRecordsEmpty: 'Termine une séance pour voir apparaître tes records ici.', statsProgressionTitle: 'Proche du palier supérieur', statsProgressionEmpty: 'Aucun exercice proche d’un palier pour l’instant.', statsProgressionSetsDetail: '{setsAtMax}/{setCount} séries à {repMax} reps', statsProgressionReady: 'Prêt à passer au palier supérieur', statsProgressionClose: 'Plus qu’une série avant le palier supérieur', statsDetailByExercise: 'Détail par exercice', statsShowMore: 'Voir {count} de plus', statsShowLess: 'Voir moins', statsGroupPush: 'Push', statsGroupPull: 'Pull', statsGroupLegs: 'Jambes',
  rest: 'repos', skip: 'Passer', workoutFinished: 'Séance terminée !', great: 'Parfait !', confirm: 'Confirmer', areYouSure: 'Es-tu sûr ?', cancel: 'Annuler', chooseOption: 'Choisir une option',
  notifications: 'Notifications', persistentNotification: 'Notification persistante', persistentNotificationDesc: "Affiche le statut du jour (repos ou entraînement) dans la barre de notifications", restTimerNotification: 'Compte à rebours dans les notifications', restTimerNotificationDesc: 'Affiche le temps de repos et l’alerte de fin dans les notifications',
  copyTemplate: 'Copier le template', aiTemplateCopied: 'Template IA copié ✓', aiTemplateCopyError: 'Impossible de copier le template',
  data: 'Données', backupFull: 'Sauvegarde complète', programsOnly: 'Programmes uniquement', calendarLegend: 'Couleur de chaque séance', calendarLegendHint: 'Afficher la légende des couleurs', calendarLegendTitle: 'Légende', calendarLegendSessionsTitle: 'Séances', calendarLegendSupplementsTitle: 'Compléments', exportData: 'Télécharger les données', exportDataDesc: 'Enregistre tes séances, programmes et compléments dans Documents au format JSON', downloadData: 'Télécharger les données', importData: 'Importer des données', importDataDesc: 'Charge une sauvegarde JSON de tes séances, programmes et compléments', import: 'Importer', exportPrograms: 'Télécharger les programmes', exportProgramsDesc: 'Enregistre uniquement tes programmes dans Documents, sans les séances', downloadPrograms: 'Télécharger les programmes', importPrograms: 'Importer des programmes', importProgramsDesc: 'Ajoute des programmes sans modifier tes séances',
  mondayShort: 'Lun', tuesdayShort: 'Mar', wednesdayShort: 'Mer', thursdayShort: 'Jeu', fridayShort: 'Ven', saturdayShort: 'Sam', sundayShort: 'Dim',
  leaveWorkout: 'Quitter la séance ?', leaveWorkoutDesc: 'Ta séance en cours ne sera pas sauvegardée.', leaveRecordedWorkout: 'Quitter la modification ?', leaveRecordedWorkoutDesc: 'Tes modifications ne seront pas enregistrées.', today: "Aujourd'hui", yesterday: 'Hier', daysAgo: 'Il y a {count}j', next: 'Suivante', method: 'Méthode', choice: 'Choix',
  previous: 'Préc: {sets} séries · {weights} kg × {reps} reps', timerNotificationTitle: 'Repos', timerNotificationBody: 'Compte à rebours en cours', timerFinishedTitle: 'Repos terminé', timerFinishedBody: 'C’est parti pour la prochaine série !', reps: 'reps', skippedExercise: 'Exercice ignoré', restore: 'Restaurer', set: 'Série', weight: 'Poids', addSet: '＋ Série', removeSet: '－ Série', skipExercise: '⊘ Ignorer l’exercice', restTime: '⏱ Lancer un repos de {time}',
  emptyWorkout: 'Séance vide', emptyWorkoutDesc: "Tu n'as enregistré aucune série. Quitter quand même ?", sets: 'séries', workoutDuration: 'durée', volume: 'volume', comparedToPrevious: 'Comparé à la séance précédente', firstWorkoutOfSession: 'Première séance enregistrée pour ce format.', workoutProgress: '{completed}/{total} exercices terminés', exerciseSetProgress: '{completed}/{total} séries terminées', exerciseCompleted: 'Exercice terminé', exerciseSkippedStatus: 'Exercice ignoré', completedExerciseOne: '{count} exercice terminé', completedExerciseMany: '{count} exercices terminés', skippedExerciseOne: '{count} exercice ignoré', skippedExerciseMany: '{count} exercices ignorés', incompleteExerciseOne: '{count} exercice incomplet', incompleteExerciseMany: '{count} exercices incomplets', finishIncompleteTitle: 'Terminer une séance incomplète ?', finishIncompleteSummary: '{completed} · {skipped} · {incomplete}. Enregistrer quand même ?', markSetComplete: 'Valider la série {number}', markSetIncomplete: 'Annuler la validation de la série {number}', markDropComplete: 'Valider le drop {number}', markDropIncomplete: 'Annuler la validation du drop {number}', workoutNote: 'Note de séance', workoutNotePlaceholder: 'Ressenti global, contexte, énergie, objectif de la prochaine séance…', programInstruction: 'Consigne du programme', noteAdd: 'Ajouter', noteSaved: 'Enregistrée', noteEmptyHint: 'Ajoute un repère pour ta prochaine séance', previousNote: 'Dernière note', previousNotePreview: 'Dernière note : {note}', reuseNote: 'Reprendre', noteAutoSave: 'Sauvegarde automatique', noteQuickPrompts: 'Raccourcis de note', notePromptTechnique: 'Technique', notePromptPain: 'Douleur', notePromptEquipment: 'Matériel', notePromptProgress: 'Progression', personalRecords: 'Nouveaux records personnels', recordWeight: '{value} kg', recordReps: '{value} reps', noDataExport: 'Aucune donnée à télécharger', exportedData: 'Données téléchargées dans Documents ✓', exportDialog: 'Télécharger les données',
  invalidExportData: 'Format de sauvegarde invalide', importConfirm: 'Cette sauvegarde remplacera tes données actuelles, y compris tes programmes. Continuer ?', importedData: 'Données importées ✓', importError: "Erreur lors de l'import", invalidJson: 'Fichier JSON invalide', fileReadError: 'Impossible de lire ce fichier. Réessaie ou choisis-en un autre.', noProgramsExport: 'Aucun programme à télécharger', exportedPrograms: 'Programmes téléchargés dans Documents ✓', importedPrograms: 'Programmes importés ✓', programsImportConfirm: 'Cette sauvegarde ajoutera les programmes importés sans modifier tes séances. Les noms similaires seront renommés. Continuer ?',
  programsHeading: 'Programmes', programsSubtitle: 'Compose chaque détail de ton entraînement.', programsTabPrograms: 'Programme', programsTabExercises: 'Exercices', create: 'Créer', customProgram: 'Créer un programme sur mesure', active: 'Actif', custom: 'sur mesure', activate: 'Activer', duplicate: 'Dupliquer', edit: 'Modifier', delete: 'Supprimer', moreActions: 'Plus d’actions', shareProgram: 'Partager ce programme', shareUnavailable: 'Le partage de fichiers n’est pas disponible sur cet appareil.',
  programsAiCardTitle: 'Créer avec une IA', programsAiCardDesc: 'Génère un programme sur mesure avec ton assistant IA préféré, puis importe-le en un clic.', programsAiCardStep1: 'Copie le template ci-dessous', programsAiCardStep2: 'Colle-le dans ton IA et décris ton objectif, ton niveau et ton matériel', programsAiCardStep3: 'Récupère le JSON généré et importe-le avec le bouton « Importer des programmes »',
  exerciseLibrary: 'Exercices', exerciseLibrarySubtitle: 'Tes exercices personnalisés, utilisables dans n’importe quel programme.', exerciseName: 'Nom de l’exercice', createExercise: 'Créer l’exercice', createNewExerciseOption: '+ Créer un nouvel exercice', noCustomExercise: 'Aucun exercice personnalisé', noCustomExerciseHelp: 'Crée un exercice pour l’utiliser dans tes programmes.', exerciseNameRequired: 'Donne un nom à cet exercice.', deleteExerciseConfirm: 'Supprimer définitivement « {name} » ?',
  builder: 'Constructeur', everythingEditable: 'Tout est modifiable manuellement', undo: 'Annuler', redo: 'Rétablir', save: 'Enregistrer', programInformation: 'Informations du programme', sessionSettings: 'Réglages de la séance', advancedOptions: 'Options avancées', collapse: 'Replier', expand: 'Déplier', programName: 'Nom du programme', programDescription: 'Description', goal: 'Objectif', level: 'Niveau', duration: 'Durée indicative', minutes: 'minutes', trainingFrequency: "Fréquence d’entraînement", frequencyInterval: 'Tous les X jours', frequencyWeekly: 'Nombre de fois par semaine', daysBetweenWorkouts: 'Jours entre les séances', sessionsPerWeek: 'Séances par semaine', intervalFrequencyHelp: 'De 1 à 30 jours', weeklyFrequencyHelp: 'De 1 à 7 séances', everyDay: 'tous les jours', everyDays: 'tous les {count} jours', oncePerWeek: '1 fois par semaine', timesPerWeek: '{count} fois par semaine',
  beginner: 'Débutant', intermediate: 'Intermédiaire', advanced: 'Avancé', addWorkout: 'Ajouter une séance', noWorkout: 'Aucune séance', addWorkoutHelp: 'Ajoute une séance pour continuer la construction.', saveActivate: 'Enregistrer et activer', workoutGoal: 'Objectif de la séance', icon: 'Icône', color: 'Couleur',
  moveLeft: 'Déplacer à gauche', moveRight: 'Déplacer à droite', deleteWorkout: 'Supprimer la séance', noBlock: 'Aucun bloc', addFirstBlock: 'Ajoute ton premier bloc ci-dessous.', addBlock: 'Ajouter un bloc', sequential: 'Séquentiel', circuit: 'Circuit', rounds: 'Rounds', exerciseRest: 'Repos exercices', roundRest: 'Repos rounds', moveUp: 'Monter', moveDown: 'Descendre', deleteBlock: 'Supprimer le bloc',
  noExercise: 'Aucun exercice', searchAddExercise: 'Recherche puis ajoute un exercice.', muscleCategory: 'Catégorie musculaire', exercise: 'Exercice', filterIn: 'Filtrer dans {category}', add: 'Ajouter', minReps: 'Reps min', maxReps: 'Reps max', rir: 'RIR', rpe: 'RPE', tempo: 'Tempo', progression: 'Progression', none: 'Aucune', doubleProgression: 'Double progression', note: 'Note', personalInstructions: 'Consignes personnelles',
  intensityTechnique: "Technique d'intensification", removeExercise: "Supprimer l'exercice", categoryFallback: 'la catégorie', programDeleteConfirm: 'Supprimer définitivement « {name} » ? Son historique de séances sera conservé.', noSearchExercise: 'Aucun exercice ne correspond à la recherche.',
  deleteRecordedWorkout: 'Supprimer cette séance', deleteRecordedWorkoutConfirm: 'Supprimer définitivement « {name} » du {date} ?', restTomorrow: '😴 Repos demain', restToday: "😴 Repos aujourd'hui", workoutCompletedToday: '✅ Séance terminée aujourd’hui', nextWorkout: 'Prochaine séance : {name}', nextWorkoutInDays: 'Dans {count} jours : {name}', tomorrowWorkout: 'Demain : {name}', workoutToday: "🏋️ {name} aujourd'hui", unknownExercise: 'Exercice inconnu', copySuffix: '{name} - copie',
  onboardingTourNote: 'Ensuite : visite express de 3 étapes · environ 30 secondes.',
  replayGuide: 'Revoir le guide complet', replayGuideDesc: 'Visite les 7 fonctions principales sans modifier tes programmes ni tes données.', replay: 'Lancer',
  backupReminderTitle: 'Pense à sauvegarder', backupReminderDesc: 'Aucune sauvegarde récente. Télécharge tes données pour ne rien perdre en cas de changement d’appareil.', backupReminderExport: 'Exporter', backupReminderDismiss: 'Ignorer le rappel de sauvegarde',
};

const EN = {
  programNotFound: 'Program not found.', lastProgramDelete: 'Create or import another program before deleting the last available program.',
  name: 'Name', newProgram: 'New program', block: 'Block', strength: 'Strength', hypertrophy: 'Hypertrophy', endurance: 'Endurance', mixed: 'Mixed', technique: 'Technique', remove: 'Remove', errorOccurred: 'An error occurred.',
  restBetweenExercises: 'Rest between exercises (s)', drops: 'Number of drops', loadReduction: 'Load reduction (%)', target: 'Target', pauses: 'Number of pauses', pauseDuration: 'Pause duration (s)', activationReps: 'Activation reps', miniSetReps: 'Reps per mini-set', techniqueRest: 'Technique rest (s)', clusterReps: 'Reps per cluster', intraSetRest: 'Intra-set rest (s)', exerciseCount: 'Number of exercises', partialReps: 'Partial reps',
  exportError: 'Download failed',
  settings: 'Settings', language: 'Language', french: 'French', english: 'English', appearance: 'Appearance', theme: 'Theme', themeDark: 'Dark', themeLight: 'Light', visualStyle: 'Visual style', visualStyleDesc: 'Changes the app’s look.', styleDefault: 'Classic', stylePiste: 'Track', styleNothing: 'Nothing', homeEyebrowNext: 'Next suggested workout', homeEyebrowSessions: 'Your workouts', privacyPolicy: 'Privacy policy', help: 'Help', replayGuide: 'Replay guide', replayGuideDesc: 'Restart the app’s guided tour.', replay: 'Replay', accessibility: 'Accessibility and comfort', textSize: 'Text size', textSizeDesc: 'Enlarge the interface without changing your data.', textSizeNormal: 'Normal', textSizeLarge: 'Large', textSizeXLarge: 'Extra large', highContrast: 'High contrast', reduceMotion: 'Reduce animations', hapticFeedback: 'Vibrate when rest ends', hapticFeedbackDesc: 'Available only on compatible devices.', keepScreenAwake: 'Keep screen awake', keepScreenAwakeDesc: 'Only during an active workout.',
  home: 'Home', calendar: 'Calendar', stats: 'Stats', programs: 'Programs',
  supplements: 'Supplements', supplementsSubtitle: 'Manage your daily intake', supplementsProgress: '{taken}/{total} taken today', supplementsEmptyHome: 'Add supplements to track them every day.', addSupplements: 'Add', manage: 'Manage', supplementName: 'Supplement name', supplementNamePlaceholder: 'e.g. Creatine', dose: 'Dose', unit: 'Unit', addSupplement: 'Add supplement', mySupplements: 'My supplements', perDay: 'per day', supplementsEmpty: 'No supplements yet.', deleteSupplementConfirm: 'Permanently delete “{name}” from your supplements?', supplementsTakenCalendar: 'Supplements taken', supplementsMissingCalendar: 'Supplements incomplete', supplementsPartialCalendar: 'Supplements partially taken',
  supplementsNotificationPending: '💊 Supplements: to take', supplementsNotificationComplete: '💊 Supplements: ✅',
  workouts: 'Workouts', streak: 'Streak 🔥', thisMonth: 'This month',
  onboardingTitle: 'Welcome to Muscu Tracker', onboardingDescription: 'Choose a suitable starting point. Everything remains editable.', onboardingProgramsLabel: 'Suggested programs', onboardingBeginner: 'Beginner full body', onboardingBeginnerDesc: '2 alternating workouts · 3 times a week · simple foundations', onboardingHypertrophy: 'Upper/Lower hypertrophy', onboardingHypertrophyDesc: '4 workouts a week · balanced volume · intermediate', onboardingStrength: 'Strength, pull-ups and deadlift', onboardingStrengthDesc: 'A/B/C/D cycle · every other day · advanced', recommended: 'Recommended', onboardingCreate: 'Create my program', onboardingCreateDesc: 'Start from a blank program and configure every workout.', onboardingImport: 'Import a program', onboardingImportDesc: 'Add a program from a JSON backup.', onboardingSkip: 'Later', homeEmptyTitle: 'No program yet', homeEmptyDescription: 'Create a custom program or start from a ready-made template to begin training.', homeEmptyCreate: 'Create my program', homeEmptyExplore: 'Discover templates', tourSkip: 'Skip guide', tourNext: 'Next', tourDone: 'Let’s go', tourStep: 'Step {current} of {total}', tourHomeTitle: 'Your home screen', tourHomeDesc: 'Find your workouts, your streak, and this month’s activity at a glance.', tourSupplementsTitle: 'Your supplements', tourSupplementsDesc: 'Add your supplements here, then tap each one to mark today’s dose taken.', tourSessionsTitle: 'Start a workout', tourSessionsDesc: 'Tap a workout to start it directly from Home.', tourCalendarTitle: 'Your history', tourCalendarDesc: 'Each color matches a workout. Expand the legend to make sense of it, and tap a day to see its detail.', tourStatsTitle: 'Your statistics', tourStatsDesc: 'Track your load and record progress, grouped by push/pull/legs.', tourProgramsTitle: 'Your programs', tourProgramsDesc: 'Fully customize your workouts: exercises, sets, and even intensity techniques like drop sets or myo-reps.', tourSettingsTitle: 'Settings', tourSettingsDesc: 'Language, theme, accessibility, notifications: it’s all here.',
  tipRestFullscreenTitle: 'Fullscreen rest', tipRestFullscreenDesc: 'Rest opens fullscreen by default. Use “Minimize” to return to the compact bar.', tipSupplementsCheckTitle: 'Mark your doses', tipSupplementsCheckDesc: 'Tap a supplement to mark it taken today.', tipTechniqueTitle: 'Intensity techniques', tipTechniqueDesc: 'Pick a technique here, like drop sets, myo-reps, or rest-pause, for this exercise.', tipSettingsTitle: 'Even more settings', tipSettingsDesc: 'Check out the Track/Nothing visual styles, and further down, accessibility (text size, contrast, vibration) and workout reminders.', gotIt: 'Got it', dismissTip: 'Dismiss tip',
  rollingCycle: 'Rolling cycle — every other day', nextSuggested: 'Next suggested workout:',
  finish: 'Finish', back: 'Back', previousMonth: 'Previous month', nextMonth: 'Next month', workoutActions: 'Workout actions', editWorkout: 'Edit workout', editWorkoutDesc: 'Add or replace exercises for this workout only.', discardWorkout: 'Discard workout', discardWorkoutConfirm: 'Discard “{name}”? Its rest timer and in-progress backup will be deleted.', bonusBlock: 'Bonus block {count}', selectBlock: 'Block to edit', newBonusBlock: '＋ New bonus block', blockName: 'Block name', blockType: 'Block type', superset: 'Superset', addExerciseToWorkout: 'Add exercise', bonusOnly: 'These changes do not modify your program.', replace: 'Replace', replaceExercise: 'Change exercise', recordedExercises: 'Recorded exercises', editingRecordedWorkout: 'Editing a recorded workout', editRecordedWorkout: 'Edit this workout', recordedWorkoutSaved: 'Workout updated ✓',
  consecutiveWorkouts: 'consecutive workouts', consecutiveWeeks: 'consecutive successful weeks', statistics: 'Statistics', performanceProgress: 'Your performance progress',
  oneMonth: '1 month', threeMonths: '3 months', sixMonths: '6 months', all: 'All',
  liftedWeight: 'Weight lifted (kg)', repetitions: 'Repetitions', noStats: 'Start training to see your stats!',
  statsRecordsTitle: 'Personal records', statsRecordsEmpty: 'Finish a workout to see your records show up here.', statsProgressionTitle: 'Close to the next level', statsProgressionEmpty: 'No exercise close to a level-up right now.', statsProgressionSetsDetail: '{setsAtMax}/{setCount} sets at {repMax} reps', statsProgressionReady: 'Ready for a load increase', statsProgressionClose: 'One set away from a load increase', statsDetailByExercise: 'Detail by exercise', statsShowMore: 'Show {count} more', statsShowLess: 'Show less', statsGroupPush: 'Push', statsGroupPull: 'Pull', statsGroupLegs: 'Legs',
  rest: 'rest', skip: 'Skip', workoutFinished: 'Workout complete!', great: 'Great!',
  confirm: 'Confirm', areYouSure: 'Are you sure?', cancel: 'Cancel', chooseOption: 'Choose an option',
  notifications: 'Notifications', persistentNotification: 'Persistent notification',
  persistentNotificationDesc: 'Shows today’s status (rest or training) in the notification bar', restTimerNotification: 'Countdown in notifications', restTimerNotificationDesc: 'Shows rest time and the completion alert in notifications',
  copyTemplate: 'Copy template', aiTemplateCopied: 'AI template copied ✓', aiTemplateCopyError: 'Could not copy the template',
  data: 'Data', backupFull: 'Full backup', programsOnly: 'Programs only', calendarLegend: 'Workout color legend', calendarLegendHint: 'Show the color legend', calendarLegendTitle: 'Legend', calendarLegendSessionsTitle: 'Workouts', calendarLegendSupplementsTitle: 'Supplements', exportData: 'Download data', exportDataDesc: 'Saves your workouts, programs, and supplements to Documents as JSON', downloadData: 'Download data',
  importData: 'Import data', importDataDesc: 'Loads a JSON backup of your workouts, programs, and supplements', import: 'Import', exportPrograms: 'Download programs', exportProgramsDesc: 'Saves only your programs to Documents, without workouts', downloadPrograms: 'Download programs', importPrograms: 'Import programs', importProgramsDesc: 'Adds programs without changing your workouts',
  mondayShort: 'Mon', tuesdayShort: 'Tue', wednesdayShort: 'Wed', thursdayShort: 'Thu', fridayShort: 'Fri', saturdayShort: 'Sat', sundayShort: 'Sun',
  leaveWorkout: 'Leave workout?', leaveWorkoutDesc: 'Your current workout will not be saved.', leaveRecordedWorkout: 'Leave editing?', leaveRecordedWorkoutDesc: 'Your changes to this recorded workout will not be saved.',
  today: 'Today', yesterday: 'Yesterday', daysAgo: '{count}d ago', next: 'Next', method: 'Method', choice: 'Choice',
  previous: 'Previous: {sets} sets · {weights} kg × {reps} reps', timerNotificationTitle: 'Rest', timerNotificationBody: 'Countdown in progress', timerFinishedTitle: 'Rest complete', timerFinishedBody: 'Time for your next set!', reps: 'reps', skippedExercise: 'Exercise skipped', restore: 'Restore',
  set: 'Set', weight: 'Weight', addSet: '＋ Set', removeSet: '－ Set', skipExercise: '⊘ Skip exercise', restTime: '⏱ Start a {time} rest',
  emptyWorkout: 'Empty workout', emptyWorkoutDesc: 'You have not recorded any sets. Leave anyway?', sets: 'sets', workoutDuration: 'duration', volume: 'volume', comparedToPrevious: 'Compared with the previous workout', firstWorkoutOfSession: 'First recorded workout for this session.', workoutProgress: '{completed}/{total} exercises completed', exerciseSetProgress: '{completed}/{total} sets completed', exerciseCompleted: 'Exercise completed', exerciseSkippedStatus: 'Exercise skipped', completedExerciseOne: '{count} exercise completed', completedExerciseMany: '{count} exercises completed', skippedExerciseOne: '{count} exercise skipped', skippedExerciseMany: '{count} exercises skipped', incompleteExerciseOne: '{count} incomplete exercise', incompleteExerciseMany: '{count} incomplete exercises', finishIncompleteTitle: 'Finish an incomplete workout?', finishIncompleteSummary: '{completed} · {skipped} · {incomplete}. Save anyway?', markSetComplete: 'Complete set {number}', markSetIncomplete: 'Mark set {number} incomplete', markDropComplete: 'Complete drop {number}', markDropIncomplete: 'Mark drop {number} incomplete', workoutNote: 'Workout note', workoutNotePlaceholder: 'Overall feeling, context, energy, objective for next time…', programInstruction: 'Program instruction', noteAdd: 'Add', noteSaved: 'Saved', noteEmptyHint: 'Add a cue for your next workout', previousNote: 'Last note', previousNotePreview: 'Last note: {note}', reuseNote: 'Reuse', noteAutoSave: 'Saved automatically', noteQuickPrompts: 'Note shortcuts', notePromptTechnique: 'Technique', notePromptPain: 'Pain', notePromptEquipment: 'Equipment', notePromptProgress: 'Progress', personalRecords: 'New personal records', recordWeight: '{value} kg', recordReps: '{value} reps',
  noDataExport: 'No data to download', exportedData: 'Data downloaded to Documents ✓', exportDialog: 'Download data',
  invalidExportData: 'Invalid backup format', importConfirm: 'This backup will replace your current data, including your programs. Continue?',
  importedData: 'Data imported ✓', importError: 'Import failed', invalidJson: 'Invalid JSON file', fileReadError: 'Could not read this file. Try again or pick another one.', noProgramsExport: 'No programs to download', exportedPrograms: 'Programs downloaded to Documents ✓', importedPrograms: 'Programs imported ✓', programsImportConfirm: 'This backup will add imported programs without changing your workouts. Similar names will be renamed. Continue?',
  programsHeading: 'Programs', programsSubtitle: 'Build every detail of your training.', programsTabPrograms: 'Program', programsTabExercises: 'Exercises', create: 'Create', customProgram: 'Create a custom program',
  active: 'Active', custom: 'custom', activate: 'Activate', duplicate: 'Duplicate', edit: 'Edit', delete: 'Delete', moreActions: 'More actions', shareProgram: 'Share this program', shareUnavailable: 'File sharing is not available on this device.',
  programsAiCardTitle: 'Create with AI', programsAiCardDesc: 'Generate a custom program with your favorite AI assistant, then import it in one tap.', programsAiCardStep1: 'Copy the template below', programsAiCardStep2: 'Paste it into your AI and describe your goal, level, and equipment', programsAiCardStep3: 'Grab the generated JSON and import it with the "Import programs" button',
  exerciseLibrary: 'Exercises', exerciseLibrarySubtitle: 'Your custom exercises, usable in any program.', exerciseName: 'Exercise name', createExercise: 'Create exercise', createNewExerciseOption: '+ Create a new exercise', noCustomExercise: 'No custom exercises yet', noCustomExerciseHelp: 'Create an exercise to use it in your programs.', exerciseNameRequired: 'Give this exercise a name.', deleteExerciseConfirm: 'Permanently delete “{name}”?',
  builder: 'Builder', everythingEditable: 'Everything can be edited manually', undo: 'Undo', redo: 'Redo', save: 'Save', programInformation: 'Program information', sessionSettings: 'Workout settings', advancedOptions: 'Advanced options', collapse: 'Collapse', expand: 'Expand',
  programName: 'Program name', programDescription: 'Description', goal: 'Goal', level: 'Level', duration: 'Estimated duration', minutes: 'minutes', trainingFrequency: 'Training frequency', frequencyInterval: 'Every X days', frequencyWeekly: 'Number of times per week', daysBetweenWorkouts: 'Days between workouts', sessionsPerWeek: 'Workouts per week', intervalFrequencyHelp: 'From 1 to 30 days', weeklyFrequencyHelp: 'From 1 to 7 workouts', everyDay: 'every day', everyDays: 'every {count} days', oncePerWeek: 'once per week', timesPerWeek: '{count} times per week',
  beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', addWorkout: 'Add workout', noWorkout: 'No workout',
  addWorkoutHelp: 'Add a workout to continue building.', saveActivate: 'Save and activate', workoutGoal: 'Workout goal', icon: 'Icon', color: 'Color',
  moveLeft: 'Move left', moveRight: 'Move right', deleteWorkout: 'Delete workout', noBlock: 'No block', addFirstBlock: 'Add your first block below.', addBlock: 'Add block',
  sequential: 'Sequential', circuit: 'Circuit', rounds: 'Rounds', exerciseRest: 'Exercise rest', roundRest: 'Round rest', moveUp: 'Move up', moveDown: 'Move down', deleteBlock: 'Delete block',
  noExercise: 'No exercise', searchAddExercise: 'Search for and add an exercise.', muscleCategory: 'Muscle group', exercise: 'Exercise', filterIn: 'Filter in {category}', add: 'Add',
  minReps: 'Min reps', maxReps: 'Max reps', rir: 'RIR', rpe: 'RPE', tempo: 'Tempo', progression: 'Progression', none: 'None', doubleProgression: 'Double progression', note: 'Note', personalInstructions: 'Personal instructions',
  intensityTechnique: 'Intensity technique', removeExercise: 'Remove exercise', categoryFallback: 'the category', programDeleteConfirm: 'Permanently delete “{name}”? Its workout history will be kept.', noSearchExercise: 'No exercise matches your search.',
  deleteRecordedWorkout: 'Delete this workout', deleteRecordedWorkoutConfirm: 'Permanently delete “{name}” from {date}?',
  restTomorrow: '😴 Rest tomorrow', restToday: '😴 Rest today', workoutCompletedToday: '✅ Workout completed today', nextWorkout: 'Next workout: {name}', nextWorkoutInDays: 'In {count} days: {name}', tomorrowWorkout: 'Tomorrow: {name}', workoutToday: '🏋️ {name} today',
  unknownExercise: 'Unknown exercise', copySuffix: '{name} - copy',
  onboardingTourNote: 'Next: a 3-step express tour · about 30 seconds.',
  replayGuide: 'Replay full guide', replayGuideDesc: 'Tour the 7 main features without changing your programs or data.', replay: 'Start',
  backupReminderTitle: 'Remember to back up', backupReminderDesc: 'No recent backup. Export your data so you don’t lose it if you switch devices.', backupReminderExport: 'Export', backupReminderDismiss: 'Dismiss backup reminder',
};

const TEXT_EN = {
  'Programme exemple — tractions & deadlift': 'Example program — pull-ups & deadlift',
  'Exemple avancé A/B/C/D, un jour sur deux, à adapter à ton matériel et à tes objectifs.': 'Advanced A/B/C/D example, every other day, to adapt to your equipment and goals.',
  'Cycle tractions et deadlift': 'Pull-up and deadlift cycle',
  'Cycle roulant A/B/C/D, un jour sur deux.': 'Rolling A/B/C/D cycle, every other day.',
  'Séance A': 'Workout A', 'Séance B': 'Workout B', 'Séance C': 'Workout C', 'Séance D': 'Workout D',
  'Tractions force + dos / biceps': 'Strength pull-ups + back / biceps', 'Push + tractions faciles': 'Push + easy pull-ups',
  'Deadlift + traction technique': 'Deadlift + pull-up technique', 'Legs + tractions endurance': 'Legs + pull-up endurance',
  'Bloc force': 'Strength block', 'Superset 1': 'Superset 1', 'Superset 2': 'Superset 2', 'Superset 3': 'Superset 3',
  'Bloc traction facile': 'Easy pull-up block', 'Bloc traction technique': 'Technique pull-up block', 'Bloc traction endurance': 'Endurance pull-up block',
  'Développé': 'Press', 'Dips ou pompes': 'Dips or push-ups', 'Hip thrust ou back ext.': 'Hip thrust or back extension',
  'Squat ou Presse': 'Squat or leg press', 'Fentes ou split squat': 'Lunges or split squat', 'Tractions endurance': 'Endurance pull-ups',
  'Chaque minute, 3 à 6 tractions': 'Every minute, perform 3 to 6 pull-ups', '1→2→3→4→5 reps, 2 à 4 cycles': '1→2→3→4→5 reps, 2 to 4 cycles',
  '30 à 50 tractions en plusieurs séries': '30 to 50 pull-ups across several sets',
  'Quand tu fais 5×5 propre, ajoute +1 à +2,5 kg': 'Once you complete a clean 5×5, add 1 to 2.5 kg',
  '50-60% de ton max, volume propre sans échec': '50-60% of your max, clean volume without failure',
  'Commence à 3 séries. Le deadlift fatigue fort.': 'Start with 3 sets. Deadlifts are highly fatiguing.',
  'Montée propre, descente contrôlée, amplitude complète': 'Clean ascent, controlled descent, full range of motion', 'Par jambe': 'Per leg',
  '⚡ Force': '⚡ Strength', '🔄 Superset': '🔄 Superset', '🎯 Traction': '🎯 Pull-up',
};

export function getLanguage() {
  const value = globalThis.localStorage?.getItem(LANGUAGE_KEY);
  return SUPPORTED_LANGUAGES.includes(value) ? value : 'fr';
}

export function t(key, variables = {}) {
  const dictionary = getLanguage() === 'en' ? EN : FR;
  const template = dictionary[key] || key;
  return Object.entries(variables).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), template);
}

export function localizeText(value) {
  if (getLanguage() !== 'en' || !value) return value;
  return TEXT_EN[value] || value;
}

export function setLanguage(language) {
  if (!SUPPORTED_LANGUAGES.includes(language)) return;
  globalThis.localStorage?.setItem(LANGUAGE_KEY, language);
  if (typeof document !== 'undefined') translateDocument();
  if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('language:changed', { detail: { language } }));
}

export function translateDocument(root = globalThis.document) {
  if (typeof document === 'undefined') return;
  document.documentElement.lang = getLanguage();
  root.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = t(element.dataset.i18n); });
  root.querySelectorAll('[data-i18n-title]').forEach((element) => { element.title = t(element.dataset.i18nTitle); });
  root.querySelectorAll('[data-i18n-aria-label]').forEach((element) => { element.setAttribute('aria-label', t(element.dataset.i18nAriaLabel)); });
  root.querySelectorAll('[data-i18n-placeholder]').forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
}
