import { getExerciseById, getExerciseDisplayName } from '../data/exercises.js';
import { DEFAULT_PROGRAM } from '../data/default-program.js';
import { formatLocalDate } from '../services/date-utils.js';
import { nowIso } from '../services/entity-meta.js';

export const CURRENT_WORKOUT_SCHEMA_VERSION = 2;
export const CURRENT_PROGRAM_SCHEMA_VERSION = 4;
export const DEFAULT_TRAINING_FREQUENCY_DAYS = 2;
export const DEFAULT_TRAINING_FREQUENCY = Object.freeze({ mode: 'interval', intervalDays: DEFAULT_TRAINING_FREQUENCY_DAYS });

const LEGACY_EXERCISE_IDS = {
  tractions_lestees: 'weighted_pull_up',
  rowing_poulie: 'cable_row',
  curl_incline: 'incline_dumbbell_curl',
  tirage_vertical_neutre: 'neutral_grip_lat_pulldown',
  face_pull_a: 'reverse_fly_machine',
  face_pull_c: 'reverse_fly_machine',
  curl_marteau: 'hammer_curl',
  gainage_suspendu: 'hanging_knee_raise',
  dev_incline_halteres: 'incline_dumbbell_press',
  elevations_laterales: 'dumbbell_lateral_raise',
  extension_triceps: 'cable_triceps_extension',
  tractions_pdc_b: 'pull_up',
  deadlift: 'barbell_deadlift',
  leg_curl: 'leg_curl',
  mollets_c: 'standing_calf_raise',
  tractions_strictes: 'pull_up',
  leg_extension: 'leg_extension',
  mollets_d: 'standing_calf_raise',
  abdos_gainage: 'plank',
  tractions_endurance: 'pull_up',
};

const LEGACY_SELECTION_IDS = {
  dev_couche: 'barbell_bench_press',
  dev_militaire: 'barbell_overhead_press',
  dips: 'dip',
  pompes_lestees: 'weighted_push_up',
  hip_thrust: 'hip_thrust',
  back_extension: 'back_extension',
  squat: 'barbell_back_squat',
  presse: 'leg_press',
  fentes: 'lunge',
  split_squat: 'split_squat',
  emom: 'emom',
  ladders: 'ladders',
  volume: 'volume',
};

const METHOD_SELECTION_IDS = new Set(['emom', 'ladders', 'volume']);

function toFiniteNumber(value, fallback = 0) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function normalizeSet(set, index) {
  return {
    setNumber: Number.isInteger(set?.setNumber) ? set.setNumber : index + 1,
    type: set?.type || 'working',
    weight: toFiniteNumber(set?.weight),
    reps: toFiniteNumber(set?.reps),
    rir: set?.rir === null || set?.rir === undefined ? null : toFiniteNumber(set.rir),
    completed: set?.completed !== false,
    segments: Array.isArray(set?.segments)
      ? set.segments.map((segment) => ({
        type: segment?.type || 'drop',
        weight: toFiniteNumber(segment?.weight),
        reps: toFiniteNumber(segment?.reps),
        completed: segment?.completed !== false,
      }))
      : [],
  };
}

function normalizeExercise(exercise) {
  const legacySelection = exercise?.selectionId || exercise?.choiceId || null;
  const selectionId = LEGACY_SELECTION_IDS[legacySelection] || legacySelection;
  const legacyId = exercise?.programExerciseId || exercise?.exerciseId || 'unknown_exercise';
  const existingCanonicalId = getExerciseById(exercise?.exerciseId) ? exercise.exerciseId : null;
  const exerciseId = selectionId && LEGACY_SELECTION_IDS[legacySelection] && !METHOD_SELECTION_IDS.has(selectionId)
    ? selectionId
    : exercise?.canonicalExerciseId || existingCanonicalId || LEGACY_EXERCISE_IDS[legacyId] || legacyId;

  return {
    ...exercise,
    programExerciseId: exercise?.programExerciseId || legacyId,
    exerciseId,
    exerciseName: exercise?.exerciseName || getExerciseDisplayName(exerciseId, legacyId),
    selectionId,
    choiceId: selectionId,
    intensityTechnique: exercise?.intensityTechnique || { type: 'straight_sets' },
    sets: Array.isArray(exercise?.sets) ? exercise.sets.map(normalizeSet) : [],
  };
}

export function getWorkoutSessionId(workout) {
  return workout?.sessionId || workout?.sessionType || null;
}

export function migrateWorkout(workout) {
  if (!workout || typeof workout !== 'object') return workout;

  const sessionId = getWorkoutSessionId(workout);
  const session = DEFAULT_PROGRAM.sessions[sessionId];
  const exercises = Array.isArray(workout.exercises)
    ? workout.exercises.map(normalizeExercise)
    : [];

  return {
    ...workout,
    schemaVersion: CURRENT_WORKOUT_SCHEMA_VERSION,
    programId: workout.programId || 'pullup_deadlift_cycle',
    programName: workout.programName || DEFAULT_PROGRAM.name,
    sessionId,
    sessionName: workout.sessionName || session?.name || sessionId,
    sessionSubtitle: workout.sessionSubtitle || session?.subtitle || '',
    sessionColorRgb: workout.sessionColorRgb || session?.colorRgb || '77, 124, 255',
    // Kept for exports generated by the old app and third-party imports.
    sessionType: sessionId,
    date: workout.date || formatLocalDate(new Date(workout.savedAt || Date.now())),
    exercises,
    // Sync bookkeeping. updatedAt falls back to savedAt (a real historical
    // timestamp) rather than "now", so a device syncing for the first time
    // doesn't make every pre-existing workout look like it just changed.
    updatedAt: workout.updatedAt || workout.savedAt || nowIso(),
    deletedAt: workout.deletedAt ?? null,
  };
}

export function migrateWorkouts(workouts) {
  if (!Array.isArray(workouts)) return { workouts: [], changed: false };
  let changed = false;
  const migrated = workouts.map((workout) => {
    const next = migrateWorkout(workout);
    if (workout?.schemaVersion !== CURRENT_WORKOUT_SCHEMA_VERSION || JSON.stringify(workout) !== JSON.stringify(next)) {
      changed = true;
    }
    return next;
  });
  return { workouts: migrated, changed };
}

export function createWorkoutRecord(workout, id, savedAt = new Date().toISOString()) {
  return migrateWorkout({
    ...workout,
    id,
    schemaVersion: CURRENT_WORKOUT_SCHEMA_VERSION,
    savedAt,
    date: workout.date || formatLocalDate(new Date(savedAt)),
  });
}

export function validateWorkout(workout) {
  const errors = [];
  if (!workout || typeof workout !== 'object') return ['Une séance doit être un objet.'];
  if (!getWorkoutSessionId(workout)) errors.push('La séance doit avoir un sessionId.');
  if (!Array.isArray(workout.exercises)) errors.push('La séance doit contenir un tableau exercises.');
  (workout.exercises || []).forEach((exercise, index) => {
    if (!exercise.programExerciseId) errors.push(`Exercice ${index + 1}: programExerciseId manquant.`);
    if (!exercise.exerciseId) errors.push(`Exercice ${index + 1}: exerciseId manquant.`);
    if (!Array.isArray(exercise.sets)) errors.push(`Exercice ${index + 1}: sets invalide.`);
  });
  return errors;
}

export function migrateProgram(program) {
  if (!program || typeof program !== 'object') return program;
  const legacyDays = Number(program.trainingFrequencyDays);
  const inputFrequency = program.trainingFrequency;
  let trainingFrequency;
  if (inputFrequency?.mode === 'weekly') {
    const sessionsPerWeek = Number(inputFrequency.sessionsPerWeek);
    trainingFrequency = {
      mode: 'weekly',
      sessionsPerWeek: Number.isInteger(sessionsPerWeek) && sessionsPerWeek >= 1 && sessionsPerWeek <= 7
        ? sessionsPerWeek
        : 3,
    };
  } else {
    const intervalDays = Number(inputFrequency?.intervalDays ?? legacyDays);
    trainingFrequency = {
      mode: 'interval',
      intervalDays: Number.isInteger(intervalDays) && intervalDays >= 1 && intervalDays <= 30
        ? intervalDays
        : DEFAULT_TRAINING_FREQUENCY_DAYS,
    };
  }
  const { trainingFrequencyDays: _legacyFrequency, ...rest } = program;
  return {
    ...rest,
    schemaVersion: CURRENT_PROGRAM_SCHEMA_VERSION,
    trainingFrequency,
    // Sync bookkeeping. Unlike workouts, programs have no pre-existing
    // historical timestamp to fall back on — this updatedAt is a migration-
    // time fabrication for any program that predates sync, not real edit
    // history. services/sync-adapters.js treats a pulled program whose id
    // already exists locally with different data as a conflict to duplicate
    // rather than overwrite, specifically because this timestamp can't be
    // trusted for last-write-wins.
    updatedAt: program.updatedAt || nowIso(),
    deletedAt: program.deletedAt ?? null,
  };
}

export function migratePrograms(programs) {
  if (!Array.isArray(programs)) return { programs: [], changed: false };
  let changed = false;
  const migrated = programs.map((program) => {
    const next = migrateProgram(program);
    if (JSON.stringify(program) !== JSON.stringify(next)) changed = true;
    return next;
  });
  return { programs: migrated, changed };
}

export function validateProgram(program) {
  const errors = [];
  if (!program || typeof program !== 'object') return ['Un programme doit être un objet.'];
  if (program.schemaVersion !== CURRENT_PROGRAM_SCHEMA_VERSION) errors.push('Version de schéma du programme invalide.');
  const frequency = program.trainingFrequency;
  if (frequency?.mode === 'interval') {
    if (!Number.isInteger(frequency.intervalDays) || frequency.intervalDays < 1 || frequency.intervalDays > 30) {
      errors.push('L’intervalle du programme doit être compris entre 1 et 30 jours.');
    }
  } else if (frequency?.mode === 'weekly') {
    if (!Number.isInteger(frequency.sessionsPerWeek) || frequency.sessionsPerWeek < 1 || frequency.sessionsPerWeek > 7) {
      errors.push('La fréquence hebdomadaire doit être comprise entre 1 et 7 séances.');
    }
  } else {
    errors.push('Le programme doit définir une fréquence valide.');
  }
  if (!Array.isArray(program.sessionOrder) || program.sessionOrder.length === 0) errors.push('Le programme doit définir sessionOrder.');
  if (!program.sessions || typeof program.sessions !== 'object') errors.push('Le programme doit définir sessions.');
  if (typeof program.name !== 'string' || !program.name.trim()) errors.push('Le programme doit avoir un nom valide.');

  (program.sessionOrder || []).forEach((sessionId) => {
    const session = program.sessions?.[sessionId];
    if (!session) {
      errors.push(`Séance ${sessionId} absente.`);
      return;
    }
    if (typeof session.id !== 'string' || session.id !== sessionId) errors.push(`Séance ${sessionId}: id incohérent.`);
    if (typeof session.name !== 'string' || !session.name.trim()) errors.push(`Séance ${sessionId}: nom invalide.`);
    if (!Array.isArray(session.blocks)) {
      errors.push(`Séance ${sessionId}: blocks invalide.`);
      return;
    }
    if (session.color && !/^#[0-9a-f]{6}$/iu.test(session.color)) errors.push(`Séance ${sessionId}: couleur invalide.`);
    (session.blocks || []).forEach((block, blockIndex) => {
      if (!Array.isArray(block.items) || block.items.length === 0) errors.push(`Bloc ${blockIndex + 1} de ${sessionId} sans items.`);
      (block.items || []).forEach((item, itemIndex) => {
        if (!item.id) errors.push(`Item ${itemIndex + 1} de ${sessionId} sans id.`);
        if (!item.exerciseId && !item.selection) errors.push(`Item ${item.id || itemIndex + 1} sans exercice ni sélection.`);
        if (!item.prescription?.repetitionRange && !item.selection?.options?.some((option) => option.prescription)) {
          errors.push(`Item ${item.id || itemIndex + 1} sans prescription.`);
        }
      });
    });
  });
  return errors;
}
